/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppKpisRouteImport } from './routes/_app.kpis'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppTeamUserIdRouteImport } from './routes/_app.team.$userId'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app.tasks.$taskId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppKpisRoute = AppKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamUserIdRoute = AppTeamUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppTeamRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppTasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/kpis': typeof AppKpisRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRouteWithChildren
  '/team': typeof AppTeamRouteWithChildren
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/team/$userId': typeof AppTeamUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/kpis': typeof AppKpisRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRouteWithChildren
  '/team': typeof AppTeamRouteWithChildren
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/team/$userId': typeof AppTeamUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/kpis': typeof AppKpisRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRouteWithChildren
  '/_app/team': typeof AppTeamRouteWithChildren
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/team/$userId': typeof AppTeamUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/attendance'
    | '/dashboard'
    | '/kpis'
    | '/notifications'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/tasks/$taskId'
    | '/team/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/attendance'
    | '/dashboard'
    | '/kpis'
    | '/notifications'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/tasks/$taskId'
    | '/team/$userId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/accept-invite'
    | '/login'
    | '/_app/attendance'
    | '/_app/dashboard'
    | '/_app/kpis'
    | '/_app/notifications'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/team'
    | '/_app/tasks/$taskId'
    | '/_app/team/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kpis': {
      id: '/_app/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof AppKpisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team/$userId': {
      id: '/_app/team/$userId'
      path: '/$userId'
      fullPath: '/team/$userId'
      preLoaderRoute: typeof AppTeamUserIdRouteImport
      parentRoute: typeof AppTeamRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppTasksRoute
    }
  }
}

interface AppTasksRouteChildren {
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
}

const AppTasksRouteChildren: AppTasksRouteChildren = {
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
}

const AppTasksRouteWithChildren = AppTasksRoute._addFileChildren(
  AppTasksRouteChildren,
)

interface AppTeamRouteChildren {
  AppTeamUserIdRoute: typeof AppTeamUserIdRoute
}

const AppTeamRouteChildren: AppTeamRouteChildren = {
  AppTeamUserIdRoute: AppTeamUserIdRoute,
}

const AppTeamRouteWithChildren =
  AppTeamRoute._addFileChildren(AppTeamRouteChildren)

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppKpisRoute: typeof AppKpisRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRouteWithChildren
  AppTeamRoute: typeof AppTeamRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppKpisRoute: AppKpisRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRouteWithChildren,
  AppTeamRoute: AppTeamRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
