/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SystemStatusRouteImport } from './routes/system-status'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HelpCentreRouteImport } from './routes/help-centre'
import { Route as CreateWorkspaceRouteImport } from './routes/create-workspace'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackSplatRouteImport } from './routes/track.$'
import { Route as ApiWebhooksRouteImport } from './routes/api/webhooks'
import { Route as ApiTranscribeVoiceNoteRouteImport } from './routes/api/transcribe-voice-note'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCalendarRouteImport } from './routes/api/calendar'
import { Route as ApiApikeysRouteImport } from './routes/api/apikeys'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as AppWorkspaceSlugRouteImport } from './routes/_app.$workspaceSlug'
import { Route as ApiWebhooksIdRouteImport } from './routes/api/webhooks.$id'
import { Route as ApiV1WorkspaceRouteImport } from './routes/api/v1/workspace'
import { Route as ApiV1TasksRouteImport } from './routes/api/v1/tasks'
import { Route as ApiV1MembersRouteImport } from './routes/api/v1/members'
import { Route as ApiV1AttendanceRouteImport } from './routes/api/v1/attendance'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api/paystack/webhook'
import { Route as ApiPaystackInitializeRouteImport } from './routes/api/paystack/initialize'
import { Route as ApiGdprExportRouteImport } from './routes/api/gdpr/export'
import { Route as ApiGdprDeleteRouteImport } from './routes/api/gdpr/delete'
import { Route as ApiCalendarTokenRouteImport } from './routes/api/calendar.$token'
import { Route as ApiApikeysIdRouteImport } from './routes/api/apikeys.$id'
import { Route as AppWorkspaceSlugTeamBoardRouteImport } from './routes/_app.$workspaceSlug.team-board'
import { Route as AppWorkspaceSlugTeamRouteImport } from './routes/_app.$workspaceSlug.team'
import { Route as AppWorkspaceSlugTasksRouteImport } from './routes/_app.$workspaceSlug.tasks'
import { Route as AppWorkspaceSlugStandupsRouteImport } from './routes/_app.$workspaceSlug.standups'
import { Route as AppWorkspaceSlugSettingsRouteImport } from './routes/_app.$workspaceSlug.settings'
import { Route as AppWorkspaceSlugReviewsRouteImport } from './routes/_app.$workspaceSlug.reviews'
import { Route as AppWorkspaceSlugReportsRouteImport } from './routes/_app.$workspaceSlug.reports'
import { Route as AppWorkspaceSlugRecurringTasksRouteImport } from './routes/_app.$workspaceSlug.recurring-tasks'
import { Route as AppWorkspaceSlugProfileRouteImport } from './routes/_app.$workspaceSlug.profile'
import { Route as AppWorkspaceSlugPayslipsRouteImport } from './routes/_app.$workspaceSlug.payslips'
import { Route as AppWorkspaceSlugOrgChartRouteImport } from './routes/_app.$workspaceSlug.org-chart'
import { Route as AppWorkspaceSlugOnboardingRouteImport } from './routes/_app.$workspaceSlug.onboarding'
import { Route as AppWorkspaceSlugOkrsRouteImport } from './routes/_app.$workspaceSlug.okrs'
import { Route as AppWorkspaceSlugNotificationsRouteImport } from './routes/_app.$workspaceSlug.notifications'
import { Route as AppWorkspaceSlugMessagesRouteImport } from './routes/_app.$workspaceSlug.messages'
import { Route as AppWorkspaceSlugLiveRouteImport } from './routes/_app.$workspaceSlug.live'
import { Route as AppWorkspaceSlugLeaveRouteImport } from './routes/_app.$workspaceSlug.leave'
import { Route as AppWorkspaceSlugKudosRouteImport } from './routes/_app.$workspaceSlug.kudos'
import { Route as AppWorkspaceSlugKpisRouteImport } from './routes/_app.$workspaceSlug.kpis'
import { Route as AppWorkspaceSlugHandbookRouteImport } from './routes/_app.$workspaceSlug.handbook'
import { Route as AppWorkspaceSlugDocumentsRouteImport } from './routes/_app.$workspaceSlug.documents'
import { Route as AppWorkspaceSlugDeliverablesRouteImport } from './routes/_app.$workspaceSlug.deliverables'
import { Route as AppWorkspaceSlugDashboardRouteImport } from './routes/_app.$workspaceSlug.dashboard'
import { Route as AppWorkspaceSlugClientProjectsRouteImport } from './routes/_app.$workspaceSlug.client-projects'
import { Route as AppWorkspaceSlugBurnoutRouteImport } from './routes/_app.$workspaceSlug.burnout'
import { Route as AppWorkspaceSlugBillingRouteImport } from './routes/_app.$workspaceSlug.billing'
import { Route as AppWorkspaceSlugAttendanceRouteImport } from './routes/_app.$workspaceSlug.attendance'
import { Route as AppWorkspaceSlugAnnouncementsRouteImport } from './routes/_app.$workspaceSlug.announcements'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicCronWeeklySummaryEmailRouteImport } from './routes/api/public/cron/weekly-summary-email'
import { Route as ApiPublicCronSubscriptionCheckRouteImport } from './routes/api/public/cron/subscription-check'
import { Route as ApiPublicCronNotificationEmailRouteImport } from './routes/api/public/cron/notification-email'
import { Route as ApiPublicCronMessageEmailRouteImport } from './routes/api/public/cron/message-email'
import { Route as ApiPublicCronLateTaskReportRouteImport } from './routes/api/public/cron/late-task-report'
import { Route as ApiPublicCronClockReminderRouteImport } from './routes/api/public/cron/clock-reminder'
import { Route as ApiPublicCronBurnoutDetectionRouteImport } from './routes/api/public/cron/burnout-detection'
import { Route as ApiPublicCronAutoClockOutRouteImport } from './routes/api/public/cron/auto-clock-out'
import { Route as AppWorkspaceSlugTeamUserIdRouteImport } from './routes/_app.$workspaceSlug.team.$userId'
import { Route as AppWorkspaceSlugTasksAssignRouteImport } from './routes/_app.$workspaceSlug.tasks_.assign'
import { Route as AppWorkspaceSlugTasksTaskIdRouteImport } from './routes/_app.$workspaceSlug.tasks_.$taskId'
import { Route as AppWorkspaceSlugSettingsAutomationsRouteImport } from './routes/_app.$workspaceSlug.settings.automations'
import { Route as AppWorkspaceSlugMessagesActivityRouteImport } from './routes/_app.$workspaceSlug.messages.activity'
import { Route as AppWorkspaceSlugMessagesDmConversationIdRouteImport } from './routes/_app.$workspaceSlug.messages.dm.$conversationId'
import { Route as AppWorkspaceSlugMessagesChannelChannelIdRouteImport } from './routes/_app.$workspaceSlug.messages.channel.$channelId'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemStatusRoute = SystemStatusRouteImport.update({
  id: '/system-status',
  path: '/system-status',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCentreRoute = HelpCentreRouteImport.update({
  id: '/help-centre',
  path: '/help-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateWorkspaceRoute = CreateWorkspaceRouteImport.update({
  id: '/create-workspace',
  path: '/create-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackSplatRoute = TrackSplatRouteImport.update({
  id: '/track/$',
  path: '/track/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksRoute = ApiWebhooksRouteImport.update({
  id: '/api/webhooks',
  path: '/api/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeVoiceNoteRoute = ApiTranscribeVoiceNoteRouteImport.update({
  id: '/api/transcribe-voice-note',
  path: '/api/transcribe-voice-note',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarRoute = ApiCalendarRouteImport.update({
  id: '/api/calendar',
  path: '/api/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApikeysRoute = ApiApikeysRouteImport.update({
  id: '/api/apikeys',
  path: '/api/apikeys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceSlugRoute = AppWorkspaceSlugRouteImport.update({
  id: '/$workspaceSlug',
  path: '/$workspaceSlug',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksIdRoute = ApiWebhooksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWebhooksRoute,
} as any)
const ApiV1WorkspaceRoute = ApiV1WorkspaceRouteImport.update({
  id: '/api/v1/workspace',
  path: '/api/v1/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TasksRoute = ApiV1TasksRouteImport.update({
  id: '/api/v1/tasks',
  path: '/api/v1/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MembersRoute = ApiV1MembersRouteImport.update({
  id: '/api/v1/members',
  path: '/api/v1/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AttendanceRoute = ApiV1AttendanceRouteImport.update({
  id: '/api/v1/attendance',
  path: '/api/v1/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack/webhook',
  path: '/api/paystack/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackInitializeRoute = ApiPaystackInitializeRouteImport.update({
  id: '/api/paystack/initialize',
  path: '/api/paystack/initialize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGdprExportRoute = ApiGdprExportRouteImport.update({
  id: '/api/gdpr/export',
  path: '/api/gdpr/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGdprDeleteRoute = ApiGdprDeleteRouteImport.update({
  id: '/api/gdpr/delete',
  path: '/api/gdpr/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarTokenRoute = ApiCalendarTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => ApiCalendarRoute,
} as any)
const ApiApikeysIdRoute = ApiApikeysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiApikeysRoute,
} as any)
const AppWorkspaceSlugTeamBoardRoute =
  AppWorkspaceSlugTeamBoardRouteImport.update({
    id: '/team-board',
    path: '/team-board',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugTeamRoute = AppWorkspaceSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugTasksRoute = AppWorkspaceSlugTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugStandupsRoute =
  AppWorkspaceSlugStandupsRouteImport.update({
    id: '/standups',
    path: '/standups',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugSettingsRoute =
  AppWorkspaceSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugReviewsRoute = AppWorkspaceSlugReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugReportsRoute = AppWorkspaceSlugReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugRecurringTasksRoute =
  AppWorkspaceSlugRecurringTasksRouteImport.update({
    id: '/recurring-tasks',
    path: '/recurring-tasks',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugProfileRoute = AppWorkspaceSlugProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugPayslipsRoute =
  AppWorkspaceSlugPayslipsRouteImport.update({
    id: '/payslips',
    path: '/payslips',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugOrgChartRoute =
  AppWorkspaceSlugOrgChartRouteImport.update({
    id: '/org-chart',
    path: '/org-chart',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugOnboardingRoute =
  AppWorkspaceSlugOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugOkrsRoute = AppWorkspaceSlugOkrsRouteImport.update({
  id: '/okrs',
  path: '/okrs',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugNotificationsRoute =
  AppWorkspaceSlugNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugMessagesRoute =
  AppWorkspaceSlugMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugLiveRoute = AppWorkspaceSlugLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugLeaveRoute = AppWorkspaceSlugLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugKudosRoute = AppWorkspaceSlugKudosRouteImport.update({
  id: '/kudos',
  path: '/kudos',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugKpisRoute = AppWorkspaceSlugKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugHandbookRoute =
  AppWorkspaceSlugHandbookRouteImport.update({
    id: '/handbook',
    path: '/handbook',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugDocumentsRoute =
  AppWorkspaceSlugDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugDeliverablesRoute =
  AppWorkspaceSlugDeliverablesRouteImport.update({
    id: '/deliverables',
    path: '/deliverables',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugDashboardRoute =
  AppWorkspaceSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugClientProjectsRoute =
  AppWorkspaceSlugClientProjectsRouteImport.update({
    id: '/client-projects',
    path: '/client-projects',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugBurnoutRoute = AppWorkspaceSlugBurnoutRouteImport.update({
  id: '/burnout',
  path: '/burnout',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugBillingRoute = AppWorkspaceSlugBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugAttendanceRoute =
  AppWorkspaceSlugAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugAnnouncementsRoute =
  AppWorkspaceSlugAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronWeeklySummaryEmailRoute =
  ApiPublicCronWeeklySummaryEmailRouteImport.update({
    id: '/api/public/cron/weekly-summary-email',
    path: '/api/public/cron/weekly-summary-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSubscriptionCheckRoute =
  ApiPublicCronSubscriptionCheckRouteImport.update({
    id: '/api/public/cron/subscription-check',
    path: '/api/public/cron/subscription-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronNotificationEmailRoute =
  ApiPublicCronNotificationEmailRouteImport.update({
    id: '/api/public/cron/notification-email',
    path: '/api/public/cron/notification-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronMessageEmailRoute =
  ApiPublicCronMessageEmailRouteImport.update({
    id: '/api/public/cron/message-email',
    path: '/api/public/cron/message-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronLateTaskReportRoute =
  ApiPublicCronLateTaskReportRouteImport.update({
    id: '/api/public/cron/late-task-report',
    path: '/api/public/cron/late-task-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronClockReminderRoute =
  ApiPublicCronClockReminderRouteImport.update({
    id: '/api/public/cron/clock-reminder',
    path: '/api/public/cron/clock-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronBurnoutDetectionRoute =
  ApiPublicCronBurnoutDetectionRouteImport.update({
    id: '/api/public/cron/burnout-detection',
    path: '/api/public/cron/burnout-detection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronAutoClockOutRoute =
  ApiPublicCronAutoClockOutRouteImport.update({
    id: '/api/public/cron/auto-clock-out',
    path: '/api/public/cron/auto-clock-out',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspaceSlugTeamUserIdRoute =
  AppWorkspaceSlugTeamUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AppWorkspaceSlugTeamRoute,
  } as any)
const AppWorkspaceSlugTasksAssignRoute =
  AppWorkspaceSlugTasksAssignRouteImport.update({
    id: '/tasks_/assign',
    path: '/tasks/assign',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugTasksTaskIdRoute =
  AppWorkspaceSlugTasksTaskIdRouteImport.update({
    id: '/tasks_/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugSettingsAutomationsRoute =
  AppWorkspaceSlugSettingsAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AppWorkspaceSlugSettingsRoute,
  } as any)
const AppWorkspaceSlugMessagesActivityRoute =
  AppWorkspaceSlugMessagesActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AppWorkspaceSlugMessagesRoute,
  } as any)
const AppWorkspaceSlugMessagesDmConversationIdRoute =
  AppWorkspaceSlugMessagesDmConversationIdRouteImport.update({
    id: '/dm/$conversationId',
    path: '/dm/$conversationId',
    getParentRoute: () => AppWorkspaceSlugMessagesRoute,
  } as any)
const AppWorkspaceSlugMessagesChannelChannelIdRoute =
  AppWorkspaceSlugMessagesChannelChannelIdRouteImport.update({
    id: '/channel/$channelId',
    path: '/channel/$channelId',
    getParentRoute: () => AppWorkspaceSlugMessagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/blog': typeof BlogRoute
  '/changelog': typeof ChangelogRoute
  '/coming-soon': typeof ComingSoonRoute
  '/cookies': typeof CookiesRoute
  '/create-workspace': typeof CreateWorkspaceRoute
  '/help-centre': typeof HelpCentreRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/super-admin': typeof SuperAdminRoute
  '/system-status': typeof SystemStatusRoute
  '/terms': typeof TermsRoute
  '/workspaces': typeof WorkspacesRoute
  '/$workspaceSlug': typeof AppWorkspaceSlugRouteWithChildren
  '/api/ai': typeof ApiAiRoute
  '/api/apikeys': typeof ApiApikeysRouteWithChildren
  '/api/calendar': typeof ApiCalendarRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/transcribe-voice-note': typeof ApiTranscribeVoiceNoteRoute
  '/api/webhooks': typeof ApiWebhooksRouteWithChildren
  '/track/$': typeof TrackSplatRoute
  '/$workspaceSlug/announcements': typeof AppWorkspaceSlugAnnouncementsRoute
  '/$workspaceSlug/attendance': typeof AppWorkspaceSlugAttendanceRoute
  '/$workspaceSlug/billing': typeof AppWorkspaceSlugBillingRoute
  '/$workspaceSlug/burnout': typeof AppWorkspaceSlugBurnoutRoute
  '/$workspaceSlug/client-projects': typeof AppWorkspaceSlugClientProjectsRoute
  '/$workspaceSlug/dashboard': typeof AppWorkspaceSlugDashboardRoute
  '/$workspaceSlug/deliverables': typeof AppWorkspaceSlugDeliverablesRoute
  '/$workspaceSlug/documents': typeof AppWorkspaceSlugDocumentsRoute
  '/$workspaceSlug/handbook': typeof AppWorkspaceSlugHandbookRoute
  '/$workspaceSlug/kpis': typeof AppWorkspaceSlugKpisRoute
  '/$workspaceSlug/kudos': typeof AppWorkspaceSlugKudosRoute
  '/$workspaceSlug/leave': typeof AppWorkspaceSlugLeaveRoute
  '/$workspaceSlug/live': typeof AppWorkspaceSlugLiveRoute
  '/$workspaceSlug/messages': typeof AppWorkspaceSlugMessagesRouteWithChildren
  '/$workspaceSlug/notifications': typeof AppWorkspaceSlugNotificationsRoute
  '/$workspaceSlug/okrs': typeof AppWorkspaceSlugOkrsRoute
  '/$workspaceSlug/onboarding': typeof AppWorkspaceSlugOnboardingRoute
  '/$workspaceSlug/org-chart': typeof AppWorkspaceSlugOrgChartRoute
  '/$workspaceSlug/payslips': typeof AppWorkspaceSlugPayslipsRoute
  '/$workspaceSlug/profile': typeof AppWorkspaceSlugProfileRoute
  '/$workspaceSlug/recurring-tasks': typeof AppWorkspaceSlugRecurringTasksRoute
  '/$workspaceSlug/reports': typeof AppWorkspaceSlugReportsRoute
  '/$workspaceSlug/reviews': typeof AppWorkspaceSlugReviewsRoute
  '/$workspaceSlug/settings': typeof AppWorkspaceSlugSettingsRouteWithChildren
  '/$workspaceSlug/standups': typeof AppWorkspaceSlugStandupsRoute
  '/$workspaceSlug/tasks': typeof AppWorkspaceSlugTasksRoute
  '/$workspaceSlug/team': typeof AppWorkspaceSlugTeamRouteWithChildren
  '/$workspaceSlug/team-board': typeof AppWorkspaceSlugTeamBoardRoute
  '/api/apikeys/$id': typeof ApiApikeysIdRoute
  '/api/calendar/$token': typeof ApiCalendarTokenRoute
  '/api/gdpr/delete': typeof ApiGdprDeleteRoute
  '/api/gdpr/export': typeof ApiGdprExportRoute
  '/api/paystack/initialize': typeof ApiPaystackInitializeRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/v1/attendance': typeof ApiV1AttendanceRoute
  '/api/v1/members': typeof ApiV1MembersRoute
  '/api/v1/tasks': typeof ApiV1TasksRoute
  '/api/v1/workspace': typeof ApiV1WorkspaceRoute
  '/api/webhooks/$id': typeof ApiWebhooksIdRoute
  '/$workspaceSlug/messages/activity': typeof AppWorkspaceSlugMessagesActivityRoute
  '/$workspaceSlug/settings/automations': typeof AppWorkspaceSlugSettingsAutomationsRoute
  '/$workspaceSlug/tasks/$taskId': typeof AppWorkspaceSlugTasksTaskIdRoute
  '/$workspaceSlug/tasks/assign': typeof AppWorkspaceSlugTasksAssignRoute
  '/$workspaceSlug/team/$userId': typeof AppWorkspaceSlugTeamUserIdRoute
  '/api/public/cron/auto-clock-out': typeof ApiPublicCronAutoClockOutRoute
  '/api/public/cron/burnout-detection': typeof ApiPublicCronBurnoutDetectionRoute
  '/api/public/cron/clock-reminder': typeof ApiPublicCronClockReminderRoute
  '/api/public/cron/late-task-report': typeof ApiPublicCronLateTaskReportRoute
  '/api/public/cron/message-email': typeof ApiPublicCronMessageEmailRoute
  '/api/public/cron/notification-email': typeof ApiPublicCronNotificationEmailRoute
  '/api/public/cron/subscription-check': typeof ApiPublicCronSubscriptionCheckRoute
  '/api/public/cron/weekly-summary-email': typeof ApiPublicCronWeeklySummaryEmailRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/$workspaceSlug/messages/channel/$channelId': typeof AppWorkspaceSlugMessagesChannelChannelIdRoute
  '/$workspaceSlug/messages/dm/$conversationId': typeof AppWorkspaceSlugMessagesDmConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/blog': typeof BlogRoute
  '/changelog': typeof ChangelogRoute
  '/coming-soon': typeof ComingSoonRoute
  '/cookies': typeof CookiesRoute
  '/create-workspace': typeof CreateWorkspaceRoute
  '/help-centre': typeof HelpCentreRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/super-admin': typeof SuperAdminRoute
  '/system-status': typeof SystemStatusRoute
  '/terms': typeof TermsRoute
  '/workspaces': typeof WorkspacesRoute
  '/$workspaceSlug': typeof AppWorkspaceSlugRouteWithChildren
  '/api/ai': typeof ApiAiRoute
  '/api/apikeys': typeof ApiApikeysRouteWithChildren
  '/api/calendar': typeof ApiCalendarRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/transcribe-voice-note': typeof ApiTranscribeVoiceNoteRoute
  '/api/webhooks': typeof ApiWebhooksRouteWithChildren
  '/track/$': typeof TrackSplatRoute
  '/$workspaceSlug/announcements': typeof AppWorkspaceSlugAnnouncementsRoute
  '/$workspaceSlug/attendance': typeof AppWorkspaceSlugAttendanceRoute
  '/$workspaceSlug/billing': typeof AppWorkspaceSlugBillingRoute
  '/$workspaceSlug/burnout': typeof AppWorkspaceSlugBurnoutRoute
  '/$workspaceSlug/client-projects': typeof AppWorkspaceSlugClientProjectsRoute
  '/$workspaceSlug/dashboard': typeof AppWorkspaceSlugDashboardRoute
  '/$workspaceSlug/deliverables': typeof AppWorkspaceSlugDeliverablesRoute
  '/$workspaceSlug/documents': typeof AppWorkspaceSlugDocumentsRoute
  '/$workspaceSlug/handbook': typeof AppWorkspaceSlugHandbookRoute
  '/$workspaceSlug/kpis': typeof AppWorkspaceSlugKpisRoute
  '/$workspaceSlug/kudos': typeof AppWorkspaceSlugKudosRoute
  '/$workspaceSlug/leave': typeof AppWorkspaceSlugLeaveRoute
  '/$workspaceSlug/live': typeof AppWorkspaceSlugLiveRoute
  '/$workspaceSlug/messages': typeof AppWorkspaceSlugMessagesRouteWithChildren
  '/$workspaceSlug/notifications': typeof AppWorkspaceSlugNotificationsRoute
  '/$workspaceSlug/okrs': typeof AppWorkspaceSlugOkrsRoute
  '/$workspaceSlug/onboarding': typeof AppWorkspaceSlugOnboardingRoute
  '/$workspaceSlug/org-chart': typeof AppWorkspaceSlugOrgChartRoute
  '/$workspaceSlug/payslips': typeof AppWorkspaceSlugPayslipsRoute
  '/$workspaceSlug/profile': typeof AppWorkspaceSlugProfileRoute
  '/$workspaceSlug/recurring-tasks': typeof AppWorkspaceSlugRecurringTasksRoute
  '/$workspaceSlug/reports': typeof AppWorkspaceSlugReportsRoute
  '/$workspaceSlug/reviews': typeof AppWorkspaceSlugReviewsRoute
  '/$workspaceSlug/settings': typeof AppWorkspaceSlugSettingsRouteWithChildren
  '/$workspaceSlug/standups': typeof AppWorkspaceSlugStandupsRoute
  '/$workspaceSlug/tasks': typeof AppWorkspaceSlugTasksRoute
  '/$workspaceSlug/team': typeof AppWorkspaceSlugTeamRouteWithChildren
  '/$workspaceSlug/team-board': typeof AppWorkspaceSlugTeamBoardRoute
  '/api/apikeys/$id': typeof ApiApikeysIdRoute
  '/api/calendar/$token': typeof ApiCalendarTokenRoute
  '/api/gdpr/delete': typeof ApiGdprDeleteRoute
  '/api/gdpr/export': typeof ApiGdprExportRoute
  '/api/paystack/initialize': typeof ApiPaystackInitializeRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/v1/attendance': typeof ApiV1AttendanceRoute
  '/api/v1/members': typeof ApiV1MembersRoute
  '/api/v1/tasks': typeof ApiV1TasksRoute
  '/api/v1/workspace': typeof ApiV1WorkspaceRoute
  '/api/webhooks/$id': typeof ApiWebhooksIdRoute
  '/$workspaceSlug/messages/activity': typeof AppWorkspaceSlugMessagesActivityRoute
  '/$workspaceSlug/settings/automations': typeof AppWorkspaceSlugSettingsAutomationsRoute
  '/$workspaceSlug/tasks/$taskId': typeof AppWorkspaceSlugTasksTaskIdRoute
  '/$workspaceSlug/tasks/assign': typeof AppWorkspaceSlugTasksAssignRoute
  '/$workspaceSlug/team/$userId': typeof AppWorkspaceSlugTeamUserIdRoute
  '/api/public/cron/auto-clock-out': typeof ApiPublicCronAutoClockOutRoute
  '/api/public/cron/burnout-detection': typeof ApiPublicCronBurnoutDetectionRoute
  '/api/public/cron/clock-reminder': typeof ApiPublicCronClockReminderRoute
  '/api/public/cron/late-task-report': typeof ApiPublicCronLateTaskReportRoute
  '/api/public/cron/message-email': typeof ApiPublicCronMessageEmailRoute
  '/api/public/cron/notification-email': typeof ApiPublicCronNotificationEmailRoute
  '/api/public/cron/subscription-check': typeof ApiPublicCronSubscriptionCheckRoute
  '/api/public/cron/weekly-summary-email': typeof ApiPublicCronWeeklySummaryEmailRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/$workspaceSlug/messages/channel/$channelId': typeof AppWorkspaceSlugMessagesChannelChannelIdRoute
  '/$workspaceSlug/messages/dm/$conversationId': typeof AppWorkspaceSlugMessagesDmConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/blog': typeof BlogRoute
  '/changelog': typeof ChangelogRoute
  '/coming-soon': typeof ComingSoonRoute
  '/cookies': typeof CookiesRoute
  '/create-workspace': typeof CreateWorkspaceRoute
  '/help-centre': typeof HelpCentreRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/super-admin': typeof SuperAdminRoute
  '/system-status': typeof SystemStatusRoute
  '/terms': typeof TermsRoute
  '/workspaces': typeof WorkspacesRoute
  '/_app/$workspaceSlug': typeof AppWorkspaceSlugRouteWithChildren
  '/api/ai': typeof ApiAiRoute
  '/api/apikeys': typeof ApiApikeysRouteWithChildren
  '/api/calendar': typeof ApiCalendarRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/transcribe-voice-note': typeof ApiTranscribeVoiceNoteRoute
  '/api/webhooks': typeof ApiWebhooksRouteWithChildren
  '/track/$': typeof TrackSplatRoute
  '/_app/$workspaceSlug/announcements': typeof AppWorkspaceSlugAnnouncementsRoute
  '/_app/$workspaceSlug/attendance': typeof AppWorkspaceSlugAttendanceRoute
  '/_app/$workspaceSlug/billing': typeof AppWorkspaceSlugBillingRoute
  '/_app/$workspaceSlug/burnout': typeof AppWorkspaceSlugBurnoutRoute
  '/_app/$workspaceSlug/client-projects': typeof AppWorkspaceSlugClientProjectsRoute
  '/_app/$workspaceSlug/dashboard': typeof AppWorkspaceSlugDashboardRoute
  '/_app/$workspaceSlug/deliverables': typeof AppWorkspaceSlugDeliverablesRoute
  '/_app/$workspaceSlug/documents': typeof AppWorkspaceSlugDocumentsRoute
  '/_app/$workspaceSlug/handbook': typeof AppWorkspaceSlugHandbookRoute
  '/_app/$workspaceSlug/kpis': typeof AppWorkspaceSlugKpisRoute
  '/_app/$workspaceSlug/kudos': typeof AppWorkspaceSlugKudosRoute
  '/_app/$workspaceSlug/leave': typeof AppWorkspaceSlugLeaveRoute
  '/_app/$workspaceSlug/live': typeof AppWorkspaceSlugLiveRoute
  '/_app/$workspaceSlug/messages': typeof AppWorkspaceSlugMessagesRouteWithChildren
  '/_app/$workspaceSlug/notifications': typeof AppWorkspaceSlugNotificationsRoute
  '/_app/$workspaceSlug/okrs': typeof AppWorkspaceSlugOkrsRoute
  '/_app/$workspaceSlug/onboarding': typeof AppWorkspaceSlugOnboardingRoute
  '/_app/$workspaceSlug/org-chart': typeof AppWorkspaceSlugOrgChartRoute
  '/_app/$workspaceSlug/payslips': typeof AppWorkspaceSlugPayslipsRoute
  '/_app/$workspaceSlug/profile': typeof AppWorkspaceSlugProfileRoute
  '/_app/$workspaceSlug/recurring-tasks': typeof AppWorkspaceSlugRecurringTasksRoute
  '/_app/$workspaceSlug/reports': typeof AppWorkspaceSlugReportsRoute
  '/_app/$workspaceSlug/reviews': typeof AppWorkspaceSlugReviewsRoute
  '/_app/$workspaceSlug/settings': typeof AppWorkspaceSlugSettingsRouteWithChildren
  '/_app/$workspaceSlug/standups': typeof AppWorkspaceSlugStandupsRoute
  '/_app/$workspaceSlug/tasks': typeof AppWorkspaceSlugTasksRoute
  '/_app/$workspaceSlug/team': typeof AppWorkspaceSlugTeamRouteWithChildren
  '/_app/$workspaceSlug/team-board': typeof AppWorkspaceSlugTeamBoardRoute
  '/api/apikeys/$id': typeof ApiApikeysIdRoute
  '/api/calendar/$token': typeof ApiCalendarTokenRoute
  '/api/gdpr/delete': typeof ApiGdprDeleteRoute
  '/api/gdpr/export': typeof ApiGdprExportRoute
  '/api/paystack/initialize': typeof ApiPaystackInitializeRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/v1/attendance': typeof ApiV1AttendanceRoute
  '/api/v1/members': typeof ApiV1MembersRoute
  '/api/v1/tasks': typeof ApiV1TasksRoute
  '/api/v1/workspace': typeof ApiV1WorkspaceRoute
  '/api/webhooks/$id': typeof ApiWebhooksIdRoute
  '/_app/$workspaceSlug/messages/activity': typeof AppWorkspaceSlugMessagesActivityRoute
  '/_app/$workspaceSlug/settings/automations': typeof AppWorkspaceSlugSettingsAutomationsRoute
  '/_app/$workspaceSlug/tasks_/$taskId': typeof AppWorkspaceSlugTasksTaskIdRoute
  '/_app/$workspaceSlug/tasks_/assign': typeof AppWorkspaceSlugTasksAssignRoute
  '/_app/$workspaceSlug/team/$userId': typeof AppWorkspaceSlugTeamUserIdRoute
  '/api/public/cron/auto-clock-out': typeof ApiPublicCronAutoClockOutRoute
  '/api/public/cron/burnout-detection': typeof ApiPublicCronBurnoutDetectionRoute
  '/api/public/cron/clock-reminder': typeof ApiPublicCronClockReminderRoute
  '/api/public/cron/late-task-report': typeof ApiPublicCronLateTaskReportRoute
  '/api/public/cron/message-email': typeof ApiPublicCronMessageEmailRoute
  '/api/public/cron/notification-email': typeof ApiPublicCronNotificationEmailRoute
  '/api/public/cron/subscription-check': typeof ApiPublicCronSubscriptionCheckRoute
  '/api/public/cron/weekly-summary-email': typeof ApiPublicCronWeeklySummaryEmailRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_app/$workspaceSlug/messages/channel/$channelId': typeof AppWorkspaceSlugMessagesChannelChannelIdRoute
  '/_app/$workspaceSlug/messages/dm/$conversationId': typeof AppWorkspaceSlugMessagesDmConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/blog'
    | '/changelog'
    | '/coming-soon'
    | '/cookies'
    | '/create-workspace'
    | '/help-centre'
    | '/join'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/status'
    | '/super-admin'
    | '/system-status'
    | '/terms'
    | '/workspaces'
    | '/$workspaceSlug'
    | '/api/ai'
    | '/api/apikeys'
    | '/api/calendar'
    | '/api/health'
    | '/api/transcribe-voice-note'
    | '/api/webhooks'
    | '/track/$'
    | '/$workspaceSlug/announcements'
    | '/$workspaceSlug/attendance'
    | '/$workspaceSlug/billing'
    | '/$workspaceSlug/burnout'
    | '/$workspaceSlug/client-projects'
    | '/$workspaceSlug/dashboard'
    | '/$workspaceSlug/deliverables'
    | '/$workspaceSlug/documents'
    | '/$workspaceSlug/handbook'
    | '/$workspaceSlug/kpis'
    | '/$workspaceSlug/kudos'
    | '/$workspaceSlug/leave'
    | '/$workspaceSlug/live'
    | '/$workspaceSlug/messages'
    | '/$workspaceSlug/notifications'
    | '/$workspaceSlug/okrs'
    | '/$workspaceSlug/onboarding'
    | '/$workspaceSlug/org-chart'
    | '/$workspaceSlug/payslips'
    | '/$workspaceSlug/profile'
    | '/$workspaceSlug/recurring-tasks'
    | '/$workspaceSlug/reports'
    | '/$workspaceSlug/reviews'
    | '/$workspaceSlug/settings'
    | '/$workspaceSlug/standups'
    | '/$workspaceSlug/tasks'
    | '/$workspaceSlug/team'
    | '/$workspaceSlug/team-board'
    | '/api/apikeys/$id'
    | '/api/calendar/$token'
    | '/api/gdpr/delete'
    | '/api/gdpr/export'
    | '/api/paystack/initialize'
    | '/api/paystack/webhook'
    | '/api/push/subscribe'
    | '/api/v1/attendance'
    | '/api/v1/members'
    | '/api/v1/tasks'
    | '/api/v1/workspace'
    | '/api/webhooks/$id'
    | '/$workspaceSlug/messages/activity'
    | '/$workspaceSlug/settings/automations'
    | '/$workspaceSlug/tasks/$taskId'
    | '/$workspaceSlug/tasks/assign'
    | '/$workspaceSlug/team/$userId'
    | '/api/public/cron/auto-clock-out'
    | '/api/public/cron/burnout-detection'
    | '/api/public/cron/clock-reminder'
    | '/api/public/cron/late-task-report'
    | '/api/public/cron/message-email'
    | '/api/public/cron/notification-email'
    | '/api/public/cron/subscription-check'
    | '/api/public/cron/weekly-summary-email'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/$workspaceSlug/messages/channel/$channelId'
    | '/$workspaceSlug/messages/dm/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/blog'
    | '/changelog'
    | '/coming-soon'
    | '/cookies'
    | '/create-workspace'
    | '/help-centre'
    | '/join'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/status'
    | '/super-admin'
    | '/system-status'
    | '/terms'
    | '/workspaces'
    | '/$workspaceSlug'
    | '/api/ai'
    | '/api/apikeys'
    | '/api/calendar'
    | '/api/health'
    | '/api/transcribe-voice-note'
    | '/api/webhooks'
    | '/track/$'
    | '/$workspaceSlug/announcements'
    | '/$workspaceSlug/attendance'
    | '/$workspaceSlug/billing'
    | '/$workspaceSlug/burnout'
    | '/$workspaceSlug/client-projects'
    | '/$workspaceSlug/dashboard'
    | '/$workspaceSlug/deliverables'
    | '/$workspaceSlug/documents'
    | '/$workspaceSlug/handbook'
    | '/$workspaceSlug/kpis'
    | '/$workspaceSlug/kudos'
    | '/$workspaceSlug/leave'
    | '/$workspaceSlug/live'
    | '/$workspaceSlug/messages'
    | '/$workspaceSlug/notifications'
    | '/$workspaceSlug/okrs'
    | '/$workspaceSlug/onboarding'
    | '/$workspaceSlug/org-chart'
    | '/$workspaceSlug/payslips'
    | '/$workspaceSlug/profile'
    | '/$workspaceSlug/recurring-tasks'
    | '/$workspaceSlug/reports'
    | '/$workspaceSlug/reviews'
    | '/$workspaceSlug/settings'
    | '/$workspaceSlug/standups'
    | '/$workspaceSlug/tasks'
    | '/$workspaceSlug/team'
    | '/$workspaceSlug/team-board'
    | '/api/apikeys/$id'
    | '/api/calendar/$token'
    | '/api/gdpr/delete'
    | '/api/gdpr/export'
    | '/api/paystack/initialize'
    | '/api/paystack/webhook'
    | '/api/push/subscribe'
    | '/api/v1/attendance'
    | '/api/v1/members'
    | '/api/v1/tasks'
    | '/api/v1/workspace'
    | '/api/webhooks/$id'
    | '/$workspaceSlug/messages/activity'
    | '/$workspaceSlug/settings/automations'
    | '/$workspaceSlug/tasks/$taskId'
    | '/$workspaceSlug/tasks/assign'
    | '/$workspaceSlug/team/$userId'
    | '/api/public/cron/auto-clock-out'
    | '/api/public/cron/burnout-detection'
    | '/api/public/cron/clock-reminder'
    | '/api/public/cron/late-task-report'
    | '/api/public/cron/message-email'
    | '/api/public/cron/notification-email'
    | '/api/public/cron/subscription-check'
    | '/api/public/cron/weekly-summary-email'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/$workspaceSlug/messages/channel/$channelId'
    | '/$workspaceSlug/messages/dm/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/accept-invite'
    | '/blog'
    | '/changelog'
    | '/coming-soon'
    | '/cookies'
    | '/create-workspace'
    | '/help-centre'
    | '/join'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/status'
    | '/super-admin'
    | '/system-status'
    | '/terms'
    | '/workspaces'
    | '/_app/$workspaceSlug'
    | '/api/ai'
    | '/api/apikeys'
    | '/api/calendar'
    | '/api/health'
    | '/api/transcribe-voice-note'
    | '/api/webhooks'
    | '/track/$'
    | '/_app/$workspaceSlug/announcements'
    | '/_app/$workspaceSlug/attendance'
    | '/_app/$workspaceSlug/billing'
    | '/_app/$workspaceSlug/burnout'
    | '/_app/$workspaceSlug/client-projects'
    | '/_app/$workspaceSlug/dashboard'
    | '/_app/$workspaceSlug/deliverables'
    | '/_app/$workspaceSlug/documents'
    | '/_app/$workspaceSlug/handbook'
    | '/_app/$workspaceSlug/kpis'
    | '/_app/$workspaceSlug/kudos'
    | '/_app/$workspaceSlug/leave'
    | '/_app/$workspaceSlug/live'
    | '/_app/$workspaceSlug/messages'
    | '/_app/$workspaceSlug/notifications'
    | '/_app/$workspaceSlug/okrs'
    | '/_app/$workspaceSlug/onboarding'
    | '/_app/$workspaceSlug/org-chart'
    | '/_app/$workspaceSlug/payslips'
    | '/_app/$workspaceSlug/profile'
    | '/_app/$workspaceSlug/recurring-tasks'
    | '/_app/$workspaceSlug/reports'
    | '/_app/$workspaceSlug/reviews'
    | '/_app/$workspaceSlug/settings'
    | '/_app/$workspaceSlug/standups'
    | '/_app/$workspaceSlug/tasks'
    | '/_app/$workspaceSlug/team'
    | '/_app/$workspaceSlug/team-board'
    | '/api/apikeys/$id'
    | '/api/calendar/$token'
    | '/api/gdpr/delete'
    | '/api/gdpr/export'
    | '/api/paystack/initialize'
    | '/api/paystack/webhook'
    | '/api/push/subscribe'
    | '/api/v1/attendance'
    | '/api/v1/members'
    | '/api/v1/tasks'
    | '/api/v1/workspace'
    | '/api/webhooks/$id'
    | '/_app/$workspaceSlug/messages/activity'
    | '/_app/$workspaceSlug/settings/automations'
    | '/_app/$workspaceSlug/tasks_/$taskId'
    | '/_app/$workspaceSlug/tasks_/assign'
    | '/_app/$workspaceSlug/team/$userId'
    | '/api/public/cron/auto-clock-out'
    | '/api/public/cron/burnout-detection'
    | '/api/public/cron/clock-reminder'
    | '/api/public/cron/late-task-report'
    | '/api/public/cron/message-email'
    | '/api/public/cron/notification-email'
    | '/api/public/cron/subscription-check'
    | '/api/public/cron/weekly-summary-email'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_app/$workspaceSlug/messages/channel/$channelId'
    | '/_app/$workspaceSlug/messages/dm/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  BlogRoute: typeof BlogRoute
  ChangelogRoute: typeof ChangelogRoute
  ComingSoonRoute: typeof ComingSoonRoute
  CookiesRoute: typeof CookiesRoute
  CreateWorkspaceRoute: typeof CreateWorkspaceRoute
  HelpCentreRoute: typeof HelpCentreRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  SuperAdminRoute: typeof SuperAdminRoute
  SystemStatusRoute: typeof SystemStatusRoute
  TermsRoute: typeof TermsRoute
  WorkspacesRoute: typeof WorkspacesRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiApikeysRoute: typeof ApiApikeysRouteWithChildren
  ApiCalendarRoute: typeof ApiCalendarRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiTranscribeVoiceNoteRoute: typeof ApiTranscribeVoiceNoteRoute
  ApiWebhooksRoute: typeof ApiWebhooksRouteWithChildren
  TrackSplatRoute: typeof TrackSplatRoute
  ApiGdprDeleteRoute: typeof ApiGdprDeleteRoute
  ApiGdprExportRoute: typeof ApiGdprExportRoute
  ApiPaystackInitializeRoute: typeof ApiPaystackInitializeRoute
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiV1AttendanceRoute: typeof ApiV1AttendanceRoute
  ApiV1MembersRoute: typeof ApiV1MembersRoute
  ApiV1TasksRoute: typeof ApiV1TasksRoute
  ApiV1WorkspaceRoute: typeof ApiV1WorkspaceRoute
  ApiPublicCronAutoClockOutRoute: typeof ApiPublicCronAutoClockOutRoute
  ApiPublicCronBurnoutDetectionRoute: typeof ApiPublicCronBurnoutDetectionRoute
  ApiPublicCronClockReminderRoute: typeof ApiPublicCronClockReminderRoute
  ApiPublicCronLateTaskReportRoute: typeof ApiPublicCronLateTaskReportRoute
  ApiPublicCronMessageEmailRoute: typeof ApiPublicCronMessageEmailRoute
  ApiPublicCronNotificationEmailRoute: typeof ApiPublicCronNotificationEmailRoute
  ApiPublicCronSubscriptionCheckRoute: typeof ApiPublicCronSubscriptionCheckRoute
  ApiPublicCronWeeklySummaryEmailRoute: typeof ApiPublicCronWeeklySummaryEmailRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-status': {
      id: '/system-status'
      path: '/system-status'
      fullPath: '/system-status'
      preLoaderRoute: typeof SystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-centre': {
      id: '/help-centre'
      path: '/help-centre'
      fullPath: '/help-centre'
      preLoaderRoute: typeof HelpCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-workspace': {
      id: '/create-workspace'
      path: '/create-workspace'
      fullPath: '/create-workspace'
      preLoaderRoute: typeof CreateWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$': {
      id: '/track/$'
      path: '/track/$'
      fullPath: '/track/$'
      preLoaderRoute: typeof TrackSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks': {
      id: '/api/webhooks'
      path: '/api/webhooks'
      fullPath: '/api/webhooks'
      preLoaderRoute: typeof ApiWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe-voice-note': {
      id: '/api/transcribe-voice-note'
      path: '/api/transcribe-voice-note'
      fullPath: '/api/transcribe-voice-note'
      preLoaderRoute: typeof ApiTranscribeVoiceNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar': {
      id: '/api/calendar'
      path: '/api/calendar'
      fullPath: '/api/calendar'
      preLoaderRoute: typeof ApiCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apikeys': {
      id: '/api/apikeys'
      path: '/api/apikeys'
      fullPath: '/api/apikeys'
      preLoaderRoute: typeof ApiApikeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$workspaceSlug': {
      id: '/_app/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug'
      preLoaderRoute: typeof AppWorkspaceSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/$id': {
      id: '/api/webhooks/$id'
      path: '/$id'
      fullPath: '/api/webhooks/$id'
      preLoaderRoute: typeof ApiWebhooksIdRouteImport
      parentRoute: typeof ApiWebhooksRoute
    }
    '/api/v1/workspace': {
      id: '/api/v1/workspace'
      path: '/api/v1/workspace'
      fullPath: '/api/v1/workspace'
      preLoaderRoute: typeof ApiV1WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tasks': {
      id: '/api/v1/tasks'
      path: '/api/v1/tasks'
      fullPath: '/api/v1/tasks'
      preLoaderRoute: typeof ApiV1TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/members': {
      id: '/api/v1/members'
      path: '/api/v1/members'
      fullPath: '/api/v1/members'
      preLoaderRoute: typeof ApiV1MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/attendance': {
      id: '/api/v1/attendance'
      path: '/api/v1/attendance'
      fullPath: '/api/v1/attendance'
      preLoaderRoute: typeof ApiV1AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/webhook': {
      id: '/api/paystack/webhook'
      path: '/api/paystack/webhook'
      fullPath: '/api/paystack/webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/initialize': {
      id: '/api/paystack/initialize'
      path: '/api/paystack/initialize'
      fullPath: '/api/paystack/initialize'
      preLoaderRoute: typeof ApiPaystackInitializeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gdpr/export': {
      id: '/api/gdpr/export'
      path: '/api/gdpr/export'
      fullPath: '/api/gdpr/export'
      preLoaderRoute: typeof ApiGdprExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gdpr/delete': {
      id: '/api/gdpr/delete'
      path: '/api/gdpr/delete'
      fullPath: '/api/gdpr/delete'
      preLoaderRoute: typeof ApiGdprDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/$token': {
      id: '/api/calendar/$token'
      path: '/$token'
      fullPath: '/api/calendar/$token'
      preLoaderRoute: typeof ApiCalendarTokenRouteImport
      parentRoute: typeof ApiCalendarRoute
    }
    '/api/apikeys/$id': {
      id: '/api/apikeys/$id'
      path: '/$id'
      fullPath: '/api/apikeys/$id'
      preLoaderRoute: typeof ApiApikeysIdRouteImport
      parentRoute: typeof ApiApikeysRoute
    }
    '/_app/$workspaceSlug/team-board': {
      id: '/_app/$workspaceSlug/team-board'
      path: '/team-board'
      fullPath: '/$workspaceSlug/team-board'
      preLoaderRoute: typeof AppWorkspaceSlugTeamBoardRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/team': {
      id: '/_app/$workspaceSlug/team'
      path: '/team'
      fullPath: '/$workspaceSlug/team'
      preLoaderRoute: typeof AppWorkspaceSlugTeamRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/tasks': {
      id: '/_app/$workspaceSlug/tasks'
      path: '/tasks'
      fullPath: '/$workspaceSlug/tasks'
      preLoaderRoute: typeof AppWorkspaceSlugTasksRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/standups': {
      id: '/_app/$workspaceSlug/standups'
      path: '/standups'
      fullPath: '/$workspaceSlug/standups'
      preLoaderRoute: typeof AppWorkspaceSlugStandupsRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/settings': {
      id: '/_app/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/$workspaceSlug/settings'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/reviews': {
      id: '/_app/$workspaceSlug/reviews'
      path: '/reviews'
      fullPath: '/$workspaceSlug/reviews'
      preLoaderRoute: typeof AppWorkspaceSlugReviewsRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/reports': {
      id: '/_app/$workspaceSlug/reports'
      path: '/reports'
      fullPath: '/$workspaceSlug/reports'
      preLoaderRoute: typeof AppWorkspaceSlugReportsRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/recurring-tasks': {
      id: '/_app/$workspaceSlug/recurring-tasks'
      path: '/recurring-tasks'
      fullPath: '/$workspaceSlug/recurring-tasks'
      preLoaderRoute: typeof AppWorkspaceSlugRecurringTasksRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/profile': {
      id: '/_app/$workspaceSlug/profile'
      path: '/profile'
      fullPath: '/$workspaceSlug/profile'
      preLoaderRoute: typeof AppWorkspaceSlugProfileRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/payslips': {
      id: '/_app/$workspaceSlug/payslips'
      path: '/payslips'
      fullPath: '/$workspaceSlug/payslips'
      preLoaderRoute: typeof AppWorkspaceSlugPayslipsRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/org-chart': {
      id: '/_app/$workspaceSlug/org-chart'
      path: '/org-chart'
      fullPath: '/$workspaceSlug/org-chart'
      preLoaderRoute: typeof AppWorkspaceSlugOrgChartRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/onboarding': {
      id: '/_app/$workspaceSlug/onboarding'
      path: '/onboarding'
      fullPath: '/$workspaceSlug/onboarding'
      preLoaderRoute: typeof AppWorkspaceSlugOnboardingRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/okrs': {
      id: '/_app/$workspaceSlug/okrs'
      path: '/okrs'
      fullPath: '/$workspaceSlug/okrs'
      preLoaderRoute: typeof AppWorkspaceSlugOkrsRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/notifications': {
      id: '/_app/$workspaceSlug/notifications'
      path: '/notifications'
      fullPath: '/$workspaceSlug/notifications'
      preLoaderRoute: typeof AppWorkspaceSlugNotificationsRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/messages': {
      id: '/_app/$workspaceSlug/messages'
      path: '/messages'
      fullPath: '/$workspaceSlug/messages'
      preLoaderRoute: typeof AppWorkspaceSlugMessagesRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/live': {
      id: '/_app/$workspaceSlug/live'
      path: '/live'
      fullPath: '/$workspaceSlug/live'
      preLoaderRoute: typeof AppWorkspaceSlugLiveRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/leave': {
      id: '/_app/$workspaceSlug/leave'
      path: '/leave'
      fullPath: '/$workspaceSlug/leave'
      preLoaderRoute: typeof AppWorkspaceSlugLeaveRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/kudos': {
      id: '/_app/$workspaceSlug/kudos'
      path: '/kudos'
      fullPath: '/$workspaceSlug/kudos'
      preLoaderRoute: typeof AppWorkspaceSlugKudosRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/kpis': {
      id: '/_app/$workspaceSlug/kpis'
      path: '/kpis'
      fullPath: '/$workspaceSlug/kpis'
      preLoaderRoute: typeof AppWorkspaceSlugKpisRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/handbook': {
      id: '/_app/$workspaceSlug/handbook'
      path: '/handbook'
      fullPath: '/$workspaceSlug/handbook'
      preLoaderRoute: typeof AppWorkspaceSlugHandbookRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/documents': {
      id: '/_app/$workspaceSlug/documents'
      path: '/documents'
      fullPath: '/$workspaceSlug/documents'
      preLoaderRoute: typeof AppWorkspaceSlugDocumentsRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/deliverables': {
      id: '/_app/$workspaceSlug/deliverables'
      path: '/deliverables'
      fullPath: '/$workspaceSlug/deliverables'
      preLoaderRoute: typeof AppWorkspaceSlugDeliverablesRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/dashboard': {
      id: '/_app/$workspaceSlug/dashboard'
      path: '/dashboard'
      fullPath: '/$workspaceSlug/dashboard'
      preLoaderRoute: typeof AppWorkspaceSlugDashboardRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/client-projects': {
      id: '/_app/$workspaceSlug/client-projects'
      path: '/client-projects'
      fullPath: '/$workspaceSlug/client-projects'
      preLoaderRoute: typeof AppWorkspaceSlugClientProjectsRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/burnout': {
      id: '/_app/$workspaceSlug/burnout'
      path: '/burnout'
      fullPath: '/$workspaceSlug/burnout'
      preLoaderRoute: typeof AppWorkspaceSlugBurnoutRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/billing': {
      id: '/_app/$workspaceSlug/billing'
      path: '/billing'
      fullPath: '/$workspaceSlug/billing'
      preLoaderRoute: typeof AppWorkspaceSlugBillingRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/attendance': {
      id: '/_app/$workspaceSlug/attendance'
      path: '/attendance'
      fullPath: '/$workspaceSlug/attendance'
      preLoaderRoute: typeof AppWorkspaceSlugAttendanceRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/announcements': {
      id: '/_app/$workspaceSlug/announcements'
      path: '/announcements'
      fullPath: '/$workspaceSlug/announcements'
      preLoaderRoute: typeof AppWorkspaceSlugAnnouncementsRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/weekly-summary-email': {
      id: '/api/public/cron/weekly-summary-email'
      path: '/api/public/cron/weekly-summary-email'
      fullPath: '/api/public/cron/weekly-summary-email'
      preLoaderRoute: typeof ApiPublicCronWeeklySummaryEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/subscription-check': {
      id: '/api/public/cron/subscription-check'
      path: '/api/public/cron/subscription-check'
      fullPath: '/api/public/cron/subscription-check'
      preLoaderRoute: typeof ApiPublicCronSubscriptionCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/notification-email': {
      id: '/api/public/cron/notification-email'
      path: '/api/public/cron/notification-email'
      fullPath: '/api/public/cron/notification-email'
      preLoaderRoute: typeof ApiPublicCronNotificationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/message-email': {
      id: '/api/public/cron/message-email'
      path: '/api/public/cron/message-email'
      fullPath: '/api/public/cron/message-email'
      preLoaderRoute: typeof ApiPublicCronMessageEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/late-task-report': {
      id: '/api/public/cron/late-task-report'
      path: '/api/public/cron/late-task-report'
      fullPath: '/api/public/cron/late-task-report'
      preLoaderRoute: typeof ApiPublicCronLateTaskReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/clock-reminder': {
      id: '/api/public/cron/clock-reminder'
      path: '/api/public/cron/clock-reminder'
      fullPath: '/api/public/cron/clock-reminder'
      preLoaderRoute: typeof ApiPublicCronClockReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/burnout-detection': {
      id: '/api/public/cron/burnout-detection'
      path: '/api/public/cron/burnout-detection'
      fullPath: '/api/public/cron/burnout-detection'
      preLoaderRoute: typeof ApiPublicCronBurnoutDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/auto-clock-out': {
      id: '/api/public/cron/auto-clock-out'
      path: '/api/public/cron/auto-clock-out'
      fullPath: '/api/public/cron/auto-clock-out'
      preLoaderRoute: typeof ApiPublicCronAutoClockOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$workspaceSlug/team/$userId': {
      id: '/_app/$workspaceSlug/team/$userId'
      path: '/$userId'
      fullPath: '/$workspaceSlug/team/$userId'
      preLoaderRoute: typeof AppWorkspaceSlugTeamUserIdRouteImport
      parentRoute: typeof AppWorkspaceSlugTeamRoute
    }
    '/_app/$workspaceSlug/tasks_/assign': {
      id: '/_app/$workspaceSlug/tasks_/assign'
      path: '/tasks/assign'
      fullPath: '/$workspaceSlug/tasks/assign'
      preLoaderRoute: typeof AppWorkspaceSlugTasksAssignRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/tasks_/$taskId': {
      id: '/_app/$workspaceSlug/tasks_/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/$workspaceSlug/tasks/$taskId'
      preLoaderRoute: typeof AppWorkspaceSlugTasksTaskIdRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/$workspaceSlug/settings/automations': {
      id: '/_app/$workspaceSlug/settings/automations'
      path: '/automations'
      fullPath: '/$workspaceSlug/settings/automations'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsAutomationsRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsRoute
    }
    '/_app/$workspaceSlug/messages/activity': {
      id: '/_app/$workspaceSlug/messages/activity'
      path: '/activity'
      fullPath: '/$workspaceSlug/messages/activity'
      preLoaderRoute: typeof AppWorkspaceSlugMessagesActivityRouteImport
      parentRoute: typeof AppWorkspaceSlugMessagesRoute
    }
    '/_app/$workspaceSlug/messages/dm/$conversationId': {
      id: '/_app/$workspaceSlug/messages/dm/$conversationId'
      path: '/dm/$conversationId'
      fullPath: '/$workspaceSlug/messages/dm/$conversationId'
      preLoaderRoute: typeof AppWorkspaceSlugMessagesDmConversationIdRouteImport
      parentRoute: typeof AppWorkspaceSlugMessagesRoute
    }
    '/_app/$workspaceSlug/messages/channel/$channelId': {
      id: '/_app/$workspaceSlug/messages/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/$workspaceSlug/messages/channel/$channelId'
      preLoaderRoute: typeof AppWorkspaceSlugMessagesChannelChannelIdRouteImport
      parentRoute: typeof AppWorkspaceSlugMessagesRoute
    }
  }
}

interface AppWorkspaceSlugMessagesRouteChildren {
  AppWorkspaceSlugMessagesActivityRoute: typeof AppWorkspaceSlugMessagesActivityRoute
  AppWorkspaceSlugMessagesChannelChannelIdRoute: typeof AppWorkspaceSlugMessagesChannelChannelIdRoute
  AppWorkspaceSlugMessagesDmConversationIdRoute: typeof AppWorkspaceSlugMessagesDmConversationIdRoute
}

const AppWorkspaceSlugMessagesRouteChildren: AppWorkspaceSlugMessagesRouteChildren =
  {
    AppWorkspaceSlugMessagesActivityRoute:
      AppWorkspaceSlugMessagesActivityRoute,
    AppWorkspaceSlugMessagesChannelChannelIdRoute:
      AppWorkspaceSlugMessagesChannelChannelIdRoute,
    AppWorkspaceSlugMessagesDmConversationIdRoute:
      AppWorkspaceSlugMessagesDmConversationIdRoute,
  }

const AppWorkspaceSlugMessagesRouteWithChildren =
  AppWorkspaceSlugMessagesRoute._addFileChildren(
    AppWorkspaceSlugMessagesRouteChildren,
  )

interface AppWorkspaceSlugSettingsRouteChildren {
  AppWorkspaceSlugSettingsAutomationsRoute: typeof AppWorkspaceSlugSettingsAutomationsRoute
}

const AppWorkspaceSlugSettingsRouteChildren: AppWorkspaceSlugSettingsRouteChildren =
  {
    AppWorkspaceSlugSettingsAutomationsRoute:
      AppWorkspaceSlugSettingsAutomationsRoute,
  }

const AppWorkspaceSlugSettingsRouteWithChildren =
  AppWorkspaceSlugSettingsRoute._addFileChildren(
    AppWorkspaceSlugSettingsRouteChildren,
  )

interface AppWorkspaceSlugTeamRouteChildren {
  AppWorkspaceSlugTeamUserIdRoute: typeof AppWorkspaceSlugTeamUserIdRoute
}

const AppWorkspaceSlugTeamRouteChildren: AppWorkspaceSlugTeamRouteChildren = {
  AppWorkspaceSlugTeamUserIdRoute: AppWorkspaceSlugTeamUserIdRoute,
}

const AppWorkspaceSlugTeamRouteWithChildren =
  AppWorkspaceSlugTeamRoute._addFileChildren(AppWorkspaceSlugTeamRouteChildren)

interface AppWorkspaceSlugRouteChildren {
  AppWorkspaceSlugAnnouncementsRoute: typeof AppWorkspaceSlugAnnouncementsRoute
  AppWorkspaceSlugAttendanceRoute: typeof AppWorkspaceSlugAttendanceRoute
  AppWorkspaceSlugBillingRoute: typeof AppWorkspaceSlugBillingRoute
  AppWorkspaceSlugBurnoutRoute: typeof AppWorkspaceSlugBurnoutRoute
  AppWorkspaceSlugClientProjectsRoute: typeof AppWorkspaceSlugClientProjectsRoute
  AppWorkspaceSlugDashboardRoute: typeof AppWorkspaceSlugDashboardRoute
  AppWorkspaceSlugDeliverablesRoute: typeof AppWorkspaceSlugDeliverablesRoute
  AppWorkspaceSlugDocumentsRoute: typeof AppWorkspaceSlugDocumentsRoute
  AppWorkspaceSlugHandbookRoute: typeof AppWorkspaceSlugHandbookRoute
  AppWorkspaceSlugKpisRoute: typeof AppWorkspaceSlugKpisRoute
  AppWorkspaceSlugKudosRoute: typeof AppWorkspaceSlugKudosRoute
  AppWorkspaceSlugLeaveRoute: typeof AppWorkspaceSlugLeaveRoute
  AppWorkspaceSlugLiveRoute: typeof AppWorkspaceSlugLiveRoute
  AppWorkspaceSlugMessagesRoute: typeof AppWorkspaceSlugMessagesRouteWithChildren
  AppWorkspaceSlugNotificationsRoute: typeof AppWorkspaceSlugNotificationsRoute
  AppWorkspaceSlugOkrsRoute: typeof AppWorkspaceSlugOkrsRoute
  AppWorkspaceSlugOnboardingRoute: typeof AppWorkspaceSlugOnboardingRoute
  AppWorkspaceSlugOrgChartRoute: typeof AppWorkspaceSlugOrgChartRoute
  AppWorkspaceSlugPayslipsRoute: typeof AppWorkspaceSlugPayslipsRoute
  AppWorkspaceSlugProfileRoute: typeof AppWorkspaceSlugProfileRoute
  AppWorkspaceSlugRecurringTasksRoute: typeof AppWorkspaceSlugRecurringTasksRoute
  AppWorkspaceSlugReportsRoute: typeof AppWorkspaceSlugReportsRoute
  AppWorkspaceSlugReviewsRoute: typeof AppWorkspaceSlugReviewsRoute
  AppWorkspaceSlugSettingsRoute: typeof AppWorkspaceSlugSettingsRouteWithChildren
  AppWorkspaceSlugStandupsRoute: typeof AppWorkspaceSlugStandupsRoute
  AppWorkspaceSlugTasksRoute: typeof AppWorkspaceSlugTasksRoute
  AppWorkspaceSlugTeamRoute: typeof AppWorkspaceSlugTeamRouteWithChildren
  AppWorkspaceSlugTeamBoardRoute: typeof AppWorkspaceSlugTeamBoardRoute
  AppWorkspaceSlugTasksTaskIdRoute: typeof AppWorkspaceSlugTasksTaskIdRoute
  AppWorkspaceSlugTasksAssignRoute: typeof AppWorkspaceSlugTasksAssignRoute
}

const AppWorkspaceSlugRouteChildren: AppWorkspaceSlugRouteChildren = {
  AppWorkspaceSlugAnnouncementsRoute: AppWorkspaceSlugAnnouncementsRoute,
  AppWorkspaceSlugAttendanceRoute: AppWorkspaceSlugAttendanceRoute,
  AppWorkspaceSlugBillingRoute: AppWorkspaceSlugBillingRoute,
  AppWorkspaceSlugBurnoutRoute: AppWorkspaceSlugBurnoutRoute,
  AppWorkspaceSlugClientProjectsRoute: AppWorkspaceSlugClientProjectsRoute,
  AppWorkspaceSlugDashboardRoute: AppWorkspaceSlugDashboardRoute,
  AppWorkspaceSlugDeliverablesRoute: AppWorkspaceSlugDeliverablesRoute,
  AppWorkspaceSlugDocumentsRoute: AppWorkspaceSlugDocumentsRoute,
  AppWorkspaceSlugHandbookRoute: AppWorkspaceSlugHandbookRoute,
  AppWorkspaceSlugKpisRoute: AppWorkspaceSlugKpisRoute,
  AppWorkspaceSlugKudosRoute: AppWorkspaceSlugKudosRoute,
  AppWorkspaceSlugLeaveRoute: AppWorkspaceSlugLeaveRoute,
  AppWorkspaceSlugLiveRoute: AppWorkspaceSlugLiveRoute,
  AppWorkspaceSlugMessagesRoute: AppWorkspaceSlugMessagesRouteWithChildren,
  AppWorkspaceSlugNotificationsRoute: AppWorkspaceSlugNotificationsRoute,
  AppWorkspaceSlugOkrsRoute: AppWorkspaceSlugOkrsRoute,
  AppWorkspaceSlugOnboardingRoute: AppWorkspaceSlugOnboardingRoute,
  AppWorkspaceSlugOrgChartRoute: AppWorkspaceSlugOrgChartRoute,
  AppWorkspaceSlugPayslipsRoute: AppWorkspaceSlugPayslipsRoute,
  AppWorkspaceSlugProfileRoute: AppWorkspaceSlugProfileRoute,
  AppWorkspaceSlugRecurringTasksRoute: AppWorkspaceSlugRecurringTasksRoute,
  AppWorkspaceSlugReportsRoute: AppWorkspaceSlugReportsRoute,
  AppWorkspaceSlugReviewsRoute: AppWorkspaceSlugReviewsRoute,
  AppWorkspaceSlugSettingsRoute: AppWorkspaceSlugSettingsRouteWithChildren,
  AppWorkspaceSlugStandupsRoute: AppWorkspaceSlugStandupsRoute,
  AppWorkspaceSlugTasksRoute: AppWorkspaceSlugTasksRoute,
  AppWorkspaceSlugTeamRoute: AppWorkspaceSlugTeamRouteWithChildren,
  AppWorkspaceSlugTeamBoardRoute: AppWorkspaceSlugTeamBoardRoute,
  AppWorkspaceSlugTasksTaskIdRoute: AppWorkspaceSlugTasksTaskIdRoute,
  AppWorkspaceSlugTasksAssignRoute: AppWorkspaceSlugTasksAssignRoute,
}

const AppWorkspaceSlugRouteWithChildren =
  AppWorkspaceSlugRoute._addFileChildren(AppWorkspaceSlugRouteChildren)

interface AppRouteChildren {
  AppWorkspaceSlugRoute: typeof AppWorkspaceSlugRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppWorkspaceSlugRoute: AppWorkspaceSlugRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiApikeysRouteChildren {
  ApiApikeysIdRoute: typeof ApiApikeysIdRoute
}

const ApiApikeysRouteChildren: ApiApikeysRouteChildren = {
  ApiApikeysIdRoute: ApiApikeysIdRoute,
}

const ApiApikeysRouteWithChildren = ApiApikeysRoute._addFileChildren(
  ApiApikeysRouteChildren,
)

interface ApiCalendarRouteChildren {
  ApiCalendarTokenRoute: typeof ApiCalendarTokenRoute
}

const ApiCalendarRouteChildren: ApiCalendarRouteChildren = {
  ApiCalendarTokenRoute: ApiCalendarTokenRoute,
}

const ApiCalendarRouteWithChildren = ApiCalendarRoute._addFileChildren(
  ApiCalendarRouteChildren,
)

interface ApiWebhooksRouteChildren {
  ApiWebhooksIdRoute: typeof ApiWebhooksIdRoute
}

const ApiWebhooksRouteChildren: ApiWebhooksRouteChildren = {
  ApiWebhooksIdRoute: ApiWebhooksIdRoute,
}

const ApiWebhooksRouteWithChildren = ApiWebhooksRoute._addFileChildren(
  ApiWebhooksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  BlogRoute: BlogRoute,
  ChangelogRoute: ChangelogRoute,
  ComingSoonRoute: ComingSoonRoute,
  CookiesRoute: CookiesRoute,
  CreateWorkspaceRoute: CreateWorkspaceRoute,
  HelpCentreRoute: HelpCentreRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  SuperAdminRoute: SuperAdminRoute,
  SystemStatusRoute: SystemStatusRoute,
  TermsRoute: TermsRoute,
  WorkspacesRoute: WorkspacesRoute,
  ApiAiRoute: ApiAiRoute,
  ApiApikeysRoute: ApiApikeysRouteWithChildren,
  ApiCalendarRoute: ApiCalendarRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiTranscribeVoiceNoteRoute: ApiTranscribeVoiceNoteRoute,
  ApiWebhooksRoute: ApiWebhooksRouteWithChildren,
  TrackSplatRoute: TrackSplatRoute,
  ApiGdprDeleteRoute: ApiGdprDeleteRoute,
  ApiGdprExportRoute: ApiGdprExportRoute,
  ApiPaystackInitializeRoute: ApiPaystackInitializeRoute,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiV1AttendanceRoute: ApiV1AttendanceRoute,
  ApiV1MembersRoute: ApiV1MembersRoute,
  ApiV1TasksRoute: ApiV1TasksRoute,
  ApiV1WorkspaceRoute: ApiV1WorkspaceRoute,
  ApiPublicCronAutoClockOutRoute: ApiPublicCronAutoClockOutRoute,
  ApiPublicCronBurnoutDetectionRoute: ApiPublicCronBurnoutDetectionRoute,
  ApiPublicCronClockReminderRoute: ApiPublicCronClockReminderRoute,
  ApiPublicCronLateTaskReportRoute: ApiPublicCronLateTaskReportRoute,
  ApiPublicCronMessageEmailRoute: ApiPublicCronMessageEmailRoute,
  ApiPublicCronNotificationEmailRoute: ApiPublicCronNotificationEmailRoute,
  ApiPublicCronSubscriptionCheckRoute: ApiPublicCronSubscriptionCheckRoute,
  ApiPublicCronWeeklySummaryEmailRoute: ApiPublicCronWeeklySummaryEmailRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
