// This file is automatically generated. Do not edit it directly.
// NOTE: The DEFAULT_* values below are intentional, hand-maintained fallbacks.
// If this file is ever regenerated, re-add them or the app will fail to boot on
// hosts that don't inject Supabase env vars at build time (e.g. Lovable).
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Public Supabase project values. The URL and the *anon/publishable* key are
// safe to ship in client bundles (they're protected by Row Level Security and
// are embedded in every browser build regardless). These match
// supabase/config.toml (project eiywowwegtwgbzrxcrck) and serve as defaults so
// the app boots even when a hosting platform fails to inject env vars at build
// time. Environment variables still override these when set.
//
// IMPORTANT: never put the service_role key here — it must stay server-only.
const DEFAULT_SUPABASE_URL = "https://eiywowwegtwgbzrxcrck.supabase.co";
const DEFAULT_SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpeXdvd3dlZ3R3Z2J6cnhjcmNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1NzYxNDIsImV4cCI6MjA5MzE1MjE0Mn0.DgKTPHiGwY7IndUdwTk3rxeoLg46sR7_FappReUGfYQ";

function createSupabaseClient() {
  // Prefer env vars when present (client-side: Vite build-time replacement of
  // import.meta.env; SSR: process.env), otherwise fall back to the public
  // defaults above so the app always has valid credentials to boot with.
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || DEFAULT_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    DEFAULT_SUPABASE_PUBLISHABLE_KEY;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
